### PR TITLE
Link Submit button with DB action, Populate park name drop-down with parks from DB, make data entry to DB work, Fix buggy park selector

### PR DESCRIPTION
**Pull request by SnakeDoc**
The drop-down re-populates itself each time it's clicked. So it should always be "fresh" even after adding a park. However this throws a massive stack trace to the console (not visible to user) when it's currently dropped-down and the user clicks on a park (since it cannot replace elements that are active). No biggie, just fyi.

The submit button is linked up, but blows up currently since we need the year and month fields to have something in them (throws a NullPointerException at the moment).

### CODE REVIEW

**Comment by ryan-apfel** [comment]
I'm not sure if clearing is very enjoyable for the user. Is there a way to
gray out the submit button until there's a change without a zillion
listeners?

**Comment by SnakeDoc** [comment]
hmm, well currently if the data is invalid, it does nothing... keeping the data in the form. It only clears if successful write into database. we should do some sort of validation/error-indicating if something is wrong... at some point... lol

**Comment by SnakeDoc** [comment]
are you thinking we should do something else instead?

**Comment by ryan-apfel** [comment]
User fills form
User hits submit
Form is submitted and submit button disabled
Form is edited, submit button re-enables.
OR unhide a green check or something and leave it there until the tab
changes.

Equating it to a word doc, I wouldn't want to have to reopen every time I
save.

**Comment by ryan-apfel** [comment]
I'm mostly concerned that we'd need a fleet of listeners do have the trap
reset itself. A one-time trigger is plenty to confirm the save button
works, however.

**Comment by SnakeDoc** [comment]
we could do something like SceneBuilder does and have a colored bar fade in near the top that says "Got it!" or "Saved!" then go away after a few seconds... leaving the data on the page until she changes month/year/or park...?

**Comment by SnakeDoc** [comment]
doing an onChangeListener for disable/re-enable button on any field edit would require a listener on all fields... probably easier to just refuse to do anything unless all mandatory fields are filled.

**Comment by SnakeDoc** [comment]
Did a few more commits...
- Made the Year and Month drop-downs work
- Fixed incorrect conversion of java.util.Date into java.sql.Date
- Fixed data types in getter when fetching the Month in data entry tab
- Fixed buggy park name selector so now it doesn't freak out when being clicked (sometimes was causing a selection to not actually become selected).

With these, we now are successfully writing data into the database (verified by logging into db and doing a SELECT COUNT(*) FROM data;).

**Comment by SnakeDoc** [comment]
@Wazoople I'd vote for merging this into master, then we'll work to fix-up the clearing on entry. for testing it at least shows us it did something without blowing up. tomorrow we'll work on a better validation and better work-flow for the real users.

**Comment by ryan-apfel** [comment]
The brief flash is perfect!

**Comment by ryan-apfel** [comment]
Seconded! I'll pull it down and tinker.

**Pull request merged**
