### PR TITLE
Created a view data tab.

### PR DESCRIPTION
**Pull request by ryan-apfel**

### CODE REVIEW

**Comment by SnakeDoc** [comment]
this one will be messy to merge. will have to merge manually by hand. i'll work on the merge today on my lunch.

**Comment by SnakeDoc** [comment]
ok, it's pretty messy. i'll need more time to manually merge... i'll tackle it when i get home

**Comment by ryan-apfel** [comment]
What makes it messy?

**Comment by SnakeDoc** [comment]
you changed lines that were also changed in a previous merge. i think
SceneBuilder re-orgs some stuff when you move things around. it's no
biggie... just can't auto-merge it when that happens.

**Comment by SnakeDoc** [comment]
fixed. wasn't so bad after all. it was because you modified the <AnchorPane> tag and added stuff which conflicted with another commit.

**Pull request merged**
